name: Crypto Monitor (WeCom-Only)

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分钟一次，可自行调整
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run monitor
        env:
          WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: python monitor.py
