name: 加密货币监控

on:
  schedule:
    # 每小时运行一次 (UTC时间)
    - cron: '0 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: 缓存依赖
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 运行监控程序
      env:
        WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
        RUN_MODE: github
      run: |
        python crypto_monitor.py
        
    - name: 上传日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7
